export const classes_without_purdue_classes = [
  {
    id: 9,
    name: "MAT111",
    school_id: 2,
    description: "Calculus 1",
    category: 2,
    group_id: null,
    pdf_id: 5,
    created_by: "x",
  },
  {
    id: 34,
    name: "BIO111",
    school_id: 2,
    description: "Biology",
    category: 4,
    group_id: null,
    pdf_id: 9,
    created_by: "x",
  },
  {
    id: 35,
    name: "BIO211",
    school_id: 2,
    description: "Bio but 2",
    category: 4,
    group_id: null,
    pdf_id: 10,
    created_by: "x",
  },
  {
    id: 37,
    name: "BIO212",
    school_id: 2,
    description: "Cell Biology",
    category: 4,
    group_id: null,
    pdf_id: 11,
    created_by: "x",
  },
  {
    id: 38,
    name: "BIO315",
    school_id: 2,
    description: "Organismal Physiology",
    category: 4,
    group_id: null,
    pdf_id: 13,
    created_by: "x",
  },
  {
    id: 39,
    name: "BIO324",
    school_id: 2,
    description: "Vascular Plants",
    category: 4,
    group_id: null,
    pdf_id: 16,
    created_by: "x",
  },
  {
    id: 40,
    name: "CHE101",
    school_id: 2,
    description: "Survey of Chemistry",
    category: 5,
    group_id: null,
    pdf_id: 18,
    created_by: "x",
  },
  {
    id: 41,
    name: "CHE111",
    school_id: 2,
    description: "General Chemistry",
    category: 5,
    group_id: null,
    pdf_id: 20,
    created_by: "x",
  },
  {
    id: 42,
    name: "CHE241",
    school_id: 2,
    description: "Inorganic Chemistry",
    category: 5,
    group_id: null,
    pdf_id: 23,
    created_by: "x",
  },
  {
    id: 43,
    name: "CHE361",
    school_id: 2,
    description: "Biochemistry",
    category: 5,
    group_id: null,
    pdf_id: 30,
    created_by: "x",
  },
  {
    id: 44,
    name: "CHE441",
    school_id: 2,
    description: "Advanced Inorganic Chemistry",
    category: 5,
    group_id: null,
    pdf_id: 34,
    created_by: "x",
  },
  {
    id: 45,
    name: "PHY110",
    school_id: 2,
    description: "Physics II - Algebra",
    category: 6,
    group_id: null,
    pdf_id: 35,
    created_by: "x",
  },
  {
    id: 46,
    name: "PHY109",
    school_id: 2,
    description: "Physics I - Algebra",
    category: 6,
    group_id: null,
    pdf_id: 37,
    created_by: "x",
  },
  {
    id: 47,
    name: "ECO101",
    school_id: 2,
    description: "Principles of Economics",
    category: 3,
    group_id: null,
    pdf_id: 42,
    created_by: "x",
  },
  {
    id: 48,
    name: "ECO262",
    school_id: 2,
    description: "Financial Markets and Institutions",
    category: 3,
    group_id: null,
    pdf_id: 48,
    created_by: "x",
  },
  {
    id: 49,
    name: "ECO277",
    school_id: 2,
    description: "Special Topics",
    category: 3,
    group_id: null,
    pdf_id: 50,
    created_by: "x",
  },
  {
    id: 50,
    name: "ECO291",
    school_id: 2,
    description: "Intermediate Microeconomic Theory",
    category: 3,
    group_id: null,
    pdf_id: 52,
    created_by: "x",
  },
  {
    id: 51,
    name: "ECO292",
    school_id: 2,
    description: "Intermediate Macroeconomics",
    category: 3,
    group_id: null,
    pdf_id: 53,
    created_by: "x",
  },
  {
    id: 52,
    name: "ECO253",
    school_id: 2,
    description: "Introduction to Econometrics",
    category: 3,
    group_id: null,
    pdf_id: 57,
    created_by: "x",
  },
  {
    id: 53,
    name: "PSY101",
    school_id: 2,
    description: "Introduction to Psychology",
    category: 7,
    group_id: null,
    pdf_id: 60,
    created_by: "x",
  },
  {
    id: 54,
    name: "PSY201",
    school_id: 2,
    description: "Research Methods & Stats I",
    category: 7,
    group_id: null,
    pdf_id: 64,
    created_by: "x",
  },
  {
    id: 55,
    name: "PSY202",
    school_id: 2,
    description: "Research Methods & Stats II",
    category: 7,
    group_id: null,
    pdf_id: 71,
    created_by: "x",
  },
  {
    id: 56,
    name: "PSY222",
    school_id: 2,
    description: "Social Psychology",
    category: 7,
    group_id: null,
    pdf_id: 74,
    created_by: "x",
  },
];

export const apps = [
  {
    id: 142,
    link: "https://education76.github.io/g77/1v1-lol-3/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "1v1.lol",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/1v1.lol-old.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 141,
    link: "https://education76.github.io/g77/1v1-lol-3/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "1v1.lol-New",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/1v1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer New",
  },
  {
    id: 143,
    link: "https://ubg100.github.io/games/2048-master/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "2048",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/2048.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 144,
    link: "https://scratch.mit.edu/projects/453281308/embed/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "2D-Fortnite",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fortnite.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting 2D",
  },
  {
    id: 145,
    link: "https://agar-io.space/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "agar.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/agar.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 284,
    link: "https://maddox.page/basic-ruffle-player/?file=alien_hominid.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Alien-Hominid",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/alien.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 146,
    link: "https://ovo-game.github.io/o/among-us/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Among-Us",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/amongus.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 147,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/gertdoro/UnityExplorer@30e7601c53b57634d2288fd993d8baaeae060eb2/CSConsole/Lexers/ab.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Angry-Birds",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/birdangry.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 148,
    link: "https://www.retrogames.cc/embed/41990-animal-crossing.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Animal-Crossing",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/animal_crossing.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator New",
  },
  {
    id: 149,
    link: "https://g.vseigru.net/10/igra-yablochnyj-rycar-mini-podzemelya/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Apple-Knight-Mini-Dungeons",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/apple-knight.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 325,
    link: "https://slope-game.github.io/arcane-archer/",
    created_at: "2024-12-02T00:43:51.930529+00:00",
    title: "Arcane-Archer",
    icon: "https://img.poki-cdn.com/cdn-cgi/image/quality=78,width=314,height=314,fit=cover,f=auto/b0969647f5a6a6ad4ecdbd64fd3eb9c6.jfif",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D Fighting",
  },
  {
    id: 150,
    link: "https://hilfig3rstorage.github.io/TGC-Storage/game-storage/src/arrowmaster.io.index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "ArrowMaster.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/arrowmaster.oi.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 285,
    link: "https://maddox.page/basic-ruffle-player/?file=awesomeTanks.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Awesome-Tanks",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/awesometanks1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 286,
    link: "https://maddox.page/basic-ruffle-player/?file=awesometanks2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Awesome-Tanks-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/awesome-tanks-2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 151,
    link: "https://thebackrooms.net/backrooms/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Backrooms",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/backrooms1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle New",
  },
  {
    id: 152,
    link: "https://topvazstore.github.io/g77/baldis-basics/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Baldis-Basics",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/baldis.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 153,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/bobydob/JSEngine@c0c9f32fd575688ff4b14309e9acf19b73f15e2a/build/bs/bs.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Basketball-Stars",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/basketball-stars.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports New",
  },
  {
    id: 219,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/9ecda005-11e9-4b52-ab9e-700b4d46d00f%2Frotoh.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Bike-Speed-Obby",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/roblox-obby-tower-or.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer New",
  },
  {
    id: 154,
    link: "//www.cdnfriv.com/gamesdata2/html5/bingo-revealer/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Bingo",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/Bingo.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 155,
    link: "https://bitlifeonline.github.io/class/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "BitLife",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bitlife.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 156,
    link: "https://igroutka.ru/loader/game/25605/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Blocky-Cars-IRL",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/real_world.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving New",
  },
  {
    id: 287,
    link: "https://maddox.page/basic-ruffle-player/?file=bloonstd.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "BloonsTD",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bloons1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 288,
    link: "https://maddox.page/basic-ruffle-player/?file=bloonstd2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Bloons-TD-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bloons2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 289,
    link: "https://maddox.page/basic-ruffle-player/?file=bloonstd3.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Bloons-TD-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bloons3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 290,
    link: "https://maddox.page/basic-ruffle-player/?file=bloxorz.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Bloxorz",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bloxorz.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 291,
    link: "https://maddox.page/basic-ruffle-player/?file=bob_robber_1.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Bob-The-Robber",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/BobTheRobber1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 292,
    link: "https://maddox.page/basic-ruffle-player/?file=breakingthebank.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Breaking-The-Bank",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/breakbank.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 157,
    link: "https://brotato.godotwebdecomp.repl.co/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Brotato-(Broken-Potato)",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/brotato.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 158,
    link: "https://g.noplayalone.com/bs/sniper-3d-fun-shooting-games",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Call-of-Duty",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/cod.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 326,
    link: "https://bitlifeonline.github.io/capybara-clicker/",
    created_at: "2024-12-03T02:46:27.660593+00:00",
    title: "Capybara-Clicker",
    icon: "https://play-lh.googleusercontent.com/qPhicF9zFY_Ya0xQm9RsTcCIKnjTb2gW5lAvzow6WgiodIOBMKyeAHaS4bh2WZN9BCU",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 159,
    link: "//www.cdnfriv.com/gamesdata2/html5/castle-defense-online/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Castle-Defender",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/castledefender.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 213,
    link: "https://scratch.mit.edu/projects/351793769/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Cat-Miner-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/cat-miner.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 281,
    link: "https://classicminecraft.github.io/games/minecraft-classic/index.html",
    created_at: "2024-12-01T23:18:22.578007+00:00",
    title: "Classic-Minecraft",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/mc-classic.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 160,
    link: "https://play.cplegacy.com/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Club-Penguin",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/clubpenguin.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 161,
    link: "https://script.google.com/macros/s/AKfycbw6e8fflbfydV7kom5id09nKaM6ix0hLlXHbs3XHOnxzrndUgPtHUHENrwKomI2Hpk3/exec",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Cluster-Rush",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/cluster_rush.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 162,
    link: "//games.poki.com/458768/combatreloaded?tag=pg-v3.71.0&amp;site_id=3&amp;iso_lang=en&amp;country=US&amp;poki_url=https://poki.com/en/g/combat-reloaded&amp;categories=65,77,93,242,385,1164&amp;special_c",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Combat-Arms-Reloaded",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/combatreloaded.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 280,
    link: "https://duckmath.org/assets/html-gabes/cookieclicker.html",
    created_at: "2024-12-01T22:39:00.673047+00:00",
    title: "Cookie-Clicker",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/cookieclicker.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 204,
    link: "https://v.gamezurs.com/brotato/hell-sucker/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Cool-Game",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/heck.png",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 164,
    link: "https://g.igroutka.ru/games/164/2afwOT8yZFmeYWGJ/2/crazy_cars/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Crazy-Cars",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/crazycars.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 165,
    link: "https://totallyscience.co/games/2024/unity/crazy-karts/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Crazy-Karts",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/crazy-karts.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 166,
    link: "https://rawcdn.githack.com/lioxryt/lioxryt-assets/d16b2cb691af033a5f3da3a496cb691c81977fc9/other/crossyroad/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "CrossyRoads",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/crossyroad.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 167,
    link: "https://unblocked-games.s3.amazonaws.com/games/2023/unity2/cs-online/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "CS-1.6-Online",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/1.6.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 168,
    link: "https://scratch.mit.edu/projects/159243389/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "CS-Surf",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/cssurf.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 169,
    link: "https://noclip.website",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Digital-Museum",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/digital.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 170,
    link: "https://ubg100.github.io/games/doodlejump/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Doodle-Jump",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/doodle.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 171,
    link: "https://emupedia.net/emupedia-game-doom1/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Doom-1",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/doom1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 172,
    link: "https://app-168468.games.s3.yandex.net/168468/p4cv0ibip04pbna98qco030k4kvl5s2n/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Draw-the-Bridge",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/draw_bridge.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle New",
  },
  {
    id: 173,
    link: "https://www.mathplayground.com/drift-boss-v3/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Drift-Boss",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/driftboss.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 174,
    link: "https://www.hoodamath.com/mobile/games/duck-life/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Duck-Life",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/dl1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 175,
    link: "https://www.hoodamath.com/mobile/games/duck-life-2-world-champion/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Duck-Life-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/dl2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 176,
    link: "https://www.hoodamath.com/mobile/games/duck-life-3-evolution/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Duck-Life-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/dl3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 177,
    link: "https://www.hoodamath.com/mobile/games/duck-life-4/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Duck-Life-4",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/dl4.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 178,
    link: "https://webglmath.github.io/eggy-car/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Eggy-Car",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/eggy-car.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 293,
    link: "https://maddox.page/basic-ruffle-player/?file=electricman2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Electric-Man-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/electric.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 179,
    link: "//www.cdnfriv.com/gamesdata1/html5/EndlessLakeSiteLocked_V1/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Endless-Lake",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/endlesslake.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 294,
    link: "https://maddox.page/basic-ruffle-player/?file=escapetheprison.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Escaping-The-Prison",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/escapeprison.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 295,
    link: "https://maddox.page/basic-ruffle-player/?file=fancypantsadventure.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Fancy-Pants-Adventures-World-1",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fancy.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 296,
    link: "https://maddox.page/basic-ruffle-player/?file=FPAWorld2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Fancy-Pants-Adventures-World-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fpaw2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 297,
    link: "https://maddox.page/basic-ruffle-player/?file=FPAWorld3.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Fancy-Pants-Adventures-World-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fpaw3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 180,
    link: "https://games.crazygames.com/en_US/fighter-aircraft-pilot/index.html?utm_source=google%2Cgoogle&utm_medium=cpc%2Ccpc&utm_campaign=google-dynamic-us%2Cgoogle-dynamic-us&ad_group=132770083907%2C13277008",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Fighter-Aircraft-Pilot",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fighter-aircraft-pilotb.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting",
  },
  {
    id: 181,
    link: "https://rawcdn.githack.com/lioxryt/lioxryt-assets/d16b2cb691af033a5f3da3a496cb691c81977fc9/other/fbwg1/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Fireboy-&-Watergirl",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fireboy.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 186,
    link: "https://iliill1.github.io/gmz/fnaf/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Five-Nights-At-Freddys",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fnaf.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 182,
    link: "https://iliill1.github.io/gmz/fnaf2/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Five-Nights-At-Freddys-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fnaf2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 183,
    link: "https://iliill1.github.io/gmz/fnaf3/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Five-Nights-At-Freddys-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fnaf3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 184,
    link: "https://iliill1.github.io/gmz/fnaf4/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Five-Nights-At-Freddys-4",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fnaf4.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 185,
    link: "https://iliill1.github.io/FNAF5/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Five-Nights-At-Freddys-5",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fnaf5.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 188,
    link: "https://scratch.mit.edu/projects/17828009/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Flappy-Bird",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/flappycircle.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "",
  },
  {
    id: 187,
    link: "https://dives05.github.io/flappyCircle/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Flappy-Circle",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/flappycircle.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 298,
    link: "https://maddox.page/basic-ruffle-player/?file=fleeingthecomplex.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Fleeing-the-Complex",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/complex.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 190,
    link: "https://s1p1.onrender.com/service/https://dashboard-cq4z.onrender.com/apps/epic-games/7308/fortnite.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Fortnite",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fortnite.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 189,
    link: "https://turbowarp.org/404950182/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Fortnite-Z",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/fortnite-z.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 299,
    link: "https://maddox.page/basic-ruffle-player/?file=freewayfury2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Freeway-Fury-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/freewayfury2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 191,
    link: "https://ubg100.github.io/games/fnf/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Friday-Night-Funkin",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/friday.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 192,
    link: "https://games.crazygames.com/en_US/funny-shooter---destroy-all/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Funny-Sh00ter",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/funntshooes.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 199,
    link: "https://pizzaedition.one/assets/mainstorage/gladihoppers.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Gadihoppers",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/gladi-hoppers.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting New",
  },
  {
    id: 195,
    link: "https://gba.cluster.ws/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "GBA-Applications",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/gba.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator",
  },
  {
    id: 197,
    link: "https://scratch.mit.edu/projects/105500895/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Geometry-Dash",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/geometrydash.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 198,
    link: "https://scratch.mit.edu/projects/389464290/embed/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Getting-Over-it",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/gettingoverit.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 200,
    link: "https://www.mathplayground.com/internal/arcademics_grand_prix.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Grand-Prix-Multiplication",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/grandprix.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 201,
    link: "https://gnhustgames.github.io/granny/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Granny",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/granny.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Horror",
  },
  {
    id: 300,
    link: "https://maddox.page/basic-ruffle-player/?file=gunball-emperor-revenge.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Gunball-Emperors-Revenge",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/gunball.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 202,
    link: "//www.cdnfriv.com/gamesdata2/html5/habbo-clicker/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Habbo-Clicker",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/habboclicker.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 203,
    link: "https://happywheelsgame.io/happy-wheels.embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Happy-Wheels",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/happpywheels.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 205,
    link: "https://hole-io.com/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Hole.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/hole.io.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 206,
    link: "https://incrediboxgames.com/wp-content/uploads/gg/incredibox-unblocked/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Incredibox",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/incredibox.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 302,
    link: "https://maddox.page/basic-ruffle-player/?file=infiltratingtheairship.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Infiltrating-the-Airship",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/airship.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 303,
    link: "https://maddox.page/basic-ruffle-player/?file=infiltratingtheairship.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "JackSmith",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/jackSmith.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 208,
    link: "https://thepizzaedition.github.io/testmkl/jetpack-joyride/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Jetpack-Joyride",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/jetpackjoyride.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 209,
    link: "https://krunker.io",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Krunker.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/krunker.io.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 304,
    link: "https://maddox.page/basic-ruffle-player/?file=learn-to-fly-2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Learn-2-Fly-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/learntofly2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 210,
    link: "https://ubg100.github.io/games/Madalin/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Madalin-Stunt-Cars-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/madalin.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 211,
    link: "https://977b60eb-ff81-4c3a-895b-b585410d6c0d.poki-gdn.com/4d251456-da04-4852-af8e-a8f068d8a93e/index.html?country=US&ccpaApplies=0&url_referrer=https%3A%2F%2Fpoki.com%2F&tag=pg-v4.4.1&site_id=3&iso_la",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Make-it-Meme",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/make-it-meme.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 212,
    link: "https://www.calculators.org/games/math-duck/game.php",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Math-Duck",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/math-duck.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 305,
    link: "https://maddox.page/basic-ruffle-player/?file=meat.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Meat-Boy",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/meat.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 282,
    link: "https://eggsalad6.github.io/",
    created_at: "2024-12-01T23:20:14.550101+00:00",
    title: "Minecraft-Multiplayer",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/mc-multiplayer.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 283,
    link: "https://sd592g.github.io/zj684od4lfg/",
    created_at: "2024-12-01T23:21:16.022649+00:00",
    title: "Minecraft-Singleplayer",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/minecraft.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 214,
    link: "https://www.hoodamath.com/mobile/games/mini-golf/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Mini-Golf",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/golfmini.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports",
  },
  {
    id: 215,
    link: "//www.cdnfriv.com/gamesdata2/html5/money-movers-1/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Money-Movers",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/moneymovers1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 216,
    link: "https://totallyscience.co/assets/games/monkey-mart/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Monkey-Mart",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/monkey-mart.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 218,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://486017395-735910036185936427.preview.editmysite.com/uploads/b/139890129-378637188943279878/files/mx3m3.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Moto-X3M",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/motox3m.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports",
  },
  {
    id: 217,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/bobydob/JSEngine@ef23f79324c37921a9e7e53dadd30c9721235820/build/m3mw/m3mw.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Moto-X3M-Winter",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/motox3mwinter.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports New",
  },
  {
    id: 220,
    link: "https://g.vseigru.net/10/igra-onli-ap-2/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Only-Up",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/onlyup.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 306,
    link: "https://maddox.page/basic-ruffle-player/?file=orion-sandbox.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Orion-Sandbox",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/meat.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 221,
    link: "https://www.echalk.co.uk/amusements/Games/Pacman/pacman.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pac-Man",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pacman.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 307,
    link: "https://maddox.page/basic-ruffle-player/?file=PapaLouie2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Papa-Louie-2:-When-Burgers-Attack",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/papalouie2_100x100%20(1).webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 308,
    link: "https://maddox.page/basic-ruffle-player/?file=PapasBurgeria.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Papas-Burgeria",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/burger.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 309,
    link: "https://maddox.page/basic-ruffle-player/?file=papasfreezeria.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Papas-Freezeria",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/icecream.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 310,
    link: "https://maddox.page/basic-ruffle-player/?file=PapasPizzeria.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Papas-Pizzeria",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/papapizza.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 311,
    link: "https://maddox.page/basic-ruffle-player/?file=papastacomia.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Papas-Tacomia",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/taco.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 222,
    link: "https://paper-io.com/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Paper.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/paper.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 223,
    link: "https://scratch.mit.edu/projects/10128407/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Paper-Minecraft",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/bird.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 224,
    link: "https://pinball.flutter.dev/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pinball",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pinball.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 225,
    link: "https://html5.gamedistribution.com/e3349d1b8c724ea5b5b8a673c89900d8/?gd_sdk_referrer_url=https%3A%2F%2Fpixelgun3d.io%2Fpixel-gun-3d",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pixel-Gun-3D",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pixelgun3d.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 226,
    link: "https://www.hoodamath.com/mobile/games/pizza-party/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pizza-Party",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pizzaparty.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 232,
    link: "https://www.miniplay.com/embed/plants-vs-zombies",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Plants-vs-Zombies",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pvz.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 227,
    link: "https://pokemonfirered--dinosaurgamer.repl.co/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pokemon-FireRed",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pokemonfirered.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator",
  },
  {
    id: 228,
    link: "https://static.arcadespot.com/retroemulator.php?system=gba&game=2015/12/pokemon-ruby.zip",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Pokemon-Ruby",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pokemonruby.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator",
  },
  {
    id: 229,
    link: "https://pizzaedition.one/assets/allgames/polytrack41/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Poly-Track",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/polytrack.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving New",
  },
  {
    id: 230,
    link: "https://thepizzaedition.github.io/JetpackJoyride/projects/portalflash/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Portal",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/portal.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 231,
    link: "https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/nurimoores/clawapps@694b2998906a8db063d73c219cf2e02a52254b4c/tsunami/bowl_radial_fgmax/ps.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "President-Simulator",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/pres_sim.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 312,
    link: "https://maddox.page/basic-ruffle-player/?file=papastacomia.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Raft-Wars",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rw1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 313,
    link: "https://maddox.page/basic-ruffle-player/?file=raftwars2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Raft-Wars-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rw2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 233,
    link: "https://bitlifeonline.github.io/rally-point/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Rally-Point",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rallypoint.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 234,
    link: "https://game316009.konggames.com/gamez/0031/6009/live/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Retro-Bowl",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/retro_bowl_icon.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports 2D",
  },
  {
    id: 235,
    link: "https://pizzaedition.one/assets/mainstorage/retrobowlcollege.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Retro-Bowl-College",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/retrobowlcollege.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Sports 2D New",
  },
  {
    id: 236,
    link: "https://s1p1.onrender.com/service/https://dashboard-cq4z.onrender.com/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Roblox",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/roblox.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 237,
    link: "https://freetoplayz.github.io/rodeo-stampede-savannah/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Rodeo-Stampede",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rodeo-stampede.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 238,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/gertdoro/RuntimeInspectorUnity@261b8428279f24e856001606cbf15e45ae072d4f/Skins/rollball.xml",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Rolling-Ball",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rollingball.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 239,
    link: "https://ubg100.github.io/games/rooftop-snipers/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Rooftop-Snipers",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/rooftop.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 240,
    link: "https://ubg100.github.io/games/run3/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Run-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/run3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 250,
    link: "https://shellshock.io/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "ShellShock.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/shell-shockers.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 242,
    link: "https://totallyscience.co/assets/games/slime-rush-td/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Slime-Rush-TD",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/slimerush.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 243,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://26515722-282596139816136697.preview.editmysite.com/uploads/b/7547235-562404422326578714/files/sis.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Slither.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/slither.io.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 244,
    link: "https://firespread01.github.io/slope/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Slope",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/slope.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 247,
    link: "https://mj89sp3sau2k7lj1eg3k40hkeppguj6j-a-sites-opensocial.googleusercontent.com/gadgets/ifr?url=http://www.gstatic.com/sites-gadgets/iframe/iframe.xml&amp;container=enterprise&amp;view=default&amp;l",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Smash-Karts",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/smashkarts.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 248,
    link: "https://drippy-cat.github.io/snowrider3D/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Snow-Rider-3D",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/snowrider3d.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving New",
  },
  {
    id: 249,
    link: "https://lagged.com/api/play2/spiral-roll3/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Spiral-Roll",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/spiralroll.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Other",
  },
  {
    id: 246,
    link: "https://www.retrogames.cc/embed/32117-super-smash-bros-usa.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "SSB64",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/smash.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator",
  },
  {
    id: 314,
    link: "https://maddox.page/basic-ruffle-player/?file=Stealing_the_Diamond.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Stealing-the-Diamond",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stealdiamond.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 252,
    link: "https://webglmath.github.io/stickmanhook/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "StickMan-Hook",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stickmanhook.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 251,
    link: "//www.cdnfriv.com/gamesdata3/html5/stickman-peacekeeper/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Stickman-Peacekeeper",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stickmanpeace.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting",
  },
  {
    id: 317,
    link: "https://maddox.page/basic-ruffle-player/?file=stormthehouse.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Storm-the-House",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stormthehouse.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 315,
    link: "https://maddox.page/basic-ruffle-player/?file=Storm_the_House_2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Storm-the-House-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/storm-the-house-2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 316,
    link: "https://maddox.page/basic-ruffle-player/?file=stormthehouse3.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Storm-the-House-3",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/storm-house-3.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 253,
    link: "https://street-shadow-classic-fighter.zurabgelashvili.repl.co",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Street-Fighter",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/street-fighter.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting",
  },
  {
    id: 254,
    link: "https://ducklife.online/stumble-guys.embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Stumble-Guys",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stumble-guy.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 256,
    link: "https://g2.igroutka.ru/games/164/WGoNK9PMd0LhDweu/subway_surfers_tokyo/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Subway-Surfers",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/subway.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 255,
    link: "https://yell0wsuit.page/assets/games/subway-surfers-unity/mexico.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Subway-Surfers-Mexico-(Broken)",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/stumble-guy.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "",
  },
  {
    id: 245,
    link: "https://3xpsmjs.pages.dev/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Super-Mario-64",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/supermario64.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Emulator",
  },
  {
    id: 257,
    link: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://57264959-967300405472742195.preview.editmysite.com/uploads/b/11886820-385538800742658772/files/smb.xml&container=ig",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Super-Mario-Bros",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/super_mario_bros_old.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D New",
  },
  {
    id: 318,
    link: "https://maddox.page/basic-ruffle-player/?file=supersmashflash2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Super-Smash-Flash-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/smashflash2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 258,
    link: "https://just-fall.github.io/j0/super-star-car/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Super-Star-Car",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/superstarcar.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 259,
    link: "https://html5.gamedistribution.com/rvvASMiM/f1c451e586c04b4c8cba01b0c50d9090/index.html?gd_sdk_referrer_url=https%3A%2F%2Fwww.miniplay.com%2Fgame%2Fsurvivor-io&mp_api_as3_url=https%3A%2F%2Fssl.minijue",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Survivor.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/survivor.io.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting",
  },
  {
    id: 319,
    link: "https://maddox.page/basic-ruffle-player/?file=SwordsandSandals2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Swords-and-Sandals-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/sas2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 260,
    link: "https://pizzaedition.one/assets/mainstorage/tabs.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "TABS",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tabs.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Fighting New",
  },
  {
    id: 261,
    link: "https://ubg100.github.io/games/tanuki/index.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Tanuki-Sunset",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tanuki.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Driving",
  },
  {
    id: 262,
    link: "https://archive777.com/Temple%20Run/Temple%20Run%202%20Game/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Temple-Run-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/templerun2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 264,
    link: "https://scratch.mit.edu/projects/451773001/embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Tetris",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tetris.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 320,
    link: "https://maddox.page/basic-ruffle-player/?file=thebindingofisaac.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "The-Binding-of-Isaac",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/isaac.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 321,
    link: "https://maddox.page/basic-ruffle-player/?file=TheImpossibleQuiz.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "The-Impossible-Quiz",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/impossible.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 301,
    link: "https://maddox.page/basic-ruffle-player/?file=TheImpossibleQuiz2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "The-Impossible-Quiz-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/impossible2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 323,
    link: "https://maddox.page/basic-ruffle-player/?file=theworldshardestgame.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "The-Worlds-Hardest-Game",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/hardgame1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 324,
    link: "https://maddox.page/basic-ruffle-player/?file=theworldshardestgame2.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "The-Worlds-Hardest-Game-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/hardgame2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 322,
    link: "https://maddox.page/basic-ruffle-player/?file=tinycastle.swf",
    created_at: "2024-12-01T23:54:26.227855+00:00",
    title: "Tiny-Castle",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tinycastle.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Flash",
  },
  {
    id: 266,
    link: "https://tribals.io/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "tribals.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tribalsio.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer New",
  },
  {
    id: 267,
    link: "https://www.friv.com/z/games/truckloader4/game.html",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Truck-Loader-4",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/truckloader4.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 268,
    link: "https://eng-docs-opensocial.googleusercontent.com/gadgets/ifr?url=https://749201648-319375013826385014.preview.editmysite.com/uploads/b/139890129-296476716652996764/files/tr.xml",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Tunnel-Rush-1",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tunnelrush1.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 269,
    link: "https://slope-game.github.io/rungame/tunnel-rush-2/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Tunnel-Rush-2",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/tunnelrush.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 270,
    link: "https://ubg98.github.io/TurnTurn/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Turn-Turn",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/turn-turn.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle New",
  },
  {
    id: 271,
    link: "https://www.hoodamath.com/mobile/games/four-colors/game.html?nocheckorient=1",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Uno",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/uno.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Puzzle",
  },
  {
    id: 272,
    link: "https://venge.io",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Venge.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/venge.io.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 273,
    link: "https://iliill1.github.io/Vex8/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Vex-8",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/vex-8.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 274,
    link: "https://slope2.online/wheres-my-water.embed",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Wheres-My-Water?",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/wheresmywater.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "2D",
  },
  {
    id: 276,
    link: "https://theunblock3dlabs.github.io/sourced/play/xx142-b2exe/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "xx142-b2.exe",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/xx142-b2.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 277,
    link: "https://html5.gamemonetize.co/ieco9m12x4vrouir7ytnupfddkucj1u2/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Yeti-Sensation",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/yetidash.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Platformer",
  },
  {
    id: 278,
    link: "https://yohoho.ws/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Yohoho.io",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/yohoho.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
  {
    id: 279,
    link: "https://zombsroyale.io/",
    created_at: "2024-12-01T21:22:25.717467+00:00",
    title: "Zombs-Royale",
    icon: "https://raw.githubusercontent.com/duckmath/icons/refs/heads/main/zombs.webp",
    is_featured: false,
    upvotes: 0,
    downvotes: 0,
    desc: null,
    categories: "Multiplayer",
  },
];
